export const REVIEWS_ARRAY = [
  {
    id: 1,
    comment: "Incredible results—looked just like a professional photo shoot!",
    headshot: "/examples/ai-portrait-1.jpg",
    avatar: "/examples/avatars/ai-portrait-1.webp",
    name: "Andrew D.",
    company: null,
    position: "Investor & Realtor",
    rating: 5,
  },
  {
    id: 2,
    comment:
      "Check out this AI-generated photo! The necklace gets a little hinky, but DAMN that looks very much like me. Very much. This is from proshoot.co if you're curious.",
    headshot: "/examples/ai-portrait-2.jpg",
    avatar: "/examples/avatars/ai-portrait-2.webp",
    name: "Valerie Leavy",
    company: null,
    position: null,
    rating: 5,
  },
  {
    id: 3,
    // comment: "Loved the ethnic integrity in my headshot, very authentic.",
    comment: "",
    headshot: "/examples/ai-portrait-3.jpg",
    avatar: "/examples/avatars/ai-portrait-3.webp",
    name: "Anton Olashyn",
    company: "Dribble",
    position: "Product Designer",
    rating: 5,
  },
  {
    id: 4,
    comment: "Amazed by how sharp and lifelike my headshot turned out.",
    headshot: "/examples/ai-portrait-4.jpg",
    avatar: "/examples/avatars/ai-portrait-4.webp",
    name: "Preeti Patel",
    company: "Innovatech",
    position: "Product Manager",
    rating: 5,
  },
  {
    id: 5,
    comment: "ProShoot.co nailed it! Perfect headshot in just 2 hours.",
    headshot: "/examples/ai-portrait-5.jpg",
    avatar: "/examples/avatars/ai-portrait-5.webp",
    name: "David H.",
    company: null,
    position: "Biologist",
    rating: 5,
  },
  {
    id: 6,
    comment:
      "Way better than traditional photography, and much cheaper. you'll love it...",
    headshot: "/examples/ai-portrait-6.jpg",
    avatar: "/examples/avatars/ai-portrait-6.webp",
    name: "J. Tyson",
    company: "F500",
    position: "Product Manager",
    rating: 4.5,
  },
  {
    id: 7,
    comment: "My headshot was flawless, no deformities at all!",
    headshot: "/examples/ai-portrait-7.jpg",
    avatar: "/examples/avatars/ai-portrait-7.webp",
    name: "Subhdaan Singh",
    company: null,
    position: "SEO Freelancer",
    rating: 5,
  },
  {
    id: 8,
    comment: "So many style options to choose from—impressed!",
    headshot: "/examples/ai-portrait-8.jpg",
    avatar: "/examples/avatars/ai-portrait-8.webp",
    name: "Ramesh Sharma",
    company: null,
    position: "Teacher",
    rating: 4,
  },
  {
    id: 9,
    comment: "Couldn’t believe the quality for the price—top-notch!",
    headshot: "/examples/ai-portrait-9.jpg",
    avatar: "/examples/avatars/ai-portrait-9.webp",
    name: "Sarah",
    company: null,
    position: "Medicine",
    rating: 5,
  },
  {
    id: 10,
    comment: "Quick and easy process with stunning results.",
    headshot: "/examples/ai-portrait-10.jpg",
    avatar: "/examples/avatars/ai-portrait-10.webp",
    name: "Deepika S.",
    company: "SS Ventures",
    position: "HR Manager",
    rating: 4.5,
  },
  {
    id: 11,
    comment: "The headshot looks like it was taken in a studio.",
    headshot: "/examples/ai-portrait-11.jpg",
    avatar: "/examples/avatars/ai-portrait-11.webp",
    name: "Daniel Foster",
    company: "Cotzero",
    position: "Digital Marketing Specialist",
    rating: 5,
  },
  {
    id: 12,
    comment: "Incredibly detailed and sharp—captured my essence perfectly.",
    headshot: "/examples/ai-portrait-12.jpg",
    avatar: "/examples/avatars/ai-portrait-12.webp",
    name: "Aadarshini",
    company: "Gravity IT",
    position: "PM",
    rating: 5,
  },
  {
    id: 13,
    comment: "Exceeded my expectations—worth every penny!",
    headshot: "/examples/ai-portrait-13.jpg",
    avatar: "/examples/avatars/ai-portrait-13.webp",
    name: "Alex W.",
    company: "Stellar Technologies",
    position: "Sales Manager",
    rating: 4,
  },
  {
    id: 14,
    comment:
      "Perfect for updating my LinkedIn profile, looks very professional.",
    headshot: "/examples/ai-portrait-14.jpg",
    avatar: "/examples/avatars/ai-portrait-14.webp",
    name: "Jiayi",
    company: null,
    position: "Medicine",
    rating: 4.5,
  },
  {
    id: 15,
    comment:
      "I needed a professional headshot for my online presence but didn't have the time for a traditional photo shoot. proshoot.co saved the day! The AI-generated image was flawless and It captured my essence perfectly. The attention to detail and realism makes it a winner in my book.",
    headshot: "/examples/ai-portrait-15.jpg",
    avatar: "/examples/avatars/ai-portrait-15.webp",
    name: "Brian",
    company: "Amazon®",
    position: "Operations Management",
    rating: 5,
  },
  {
    id: 16,
    comment: "Fast turnaround, and the quality was amazing!",
    headshot: "/examples/ai-portrait-16.jpg",
    avatar: "/examples/avatars/ai-portrait-16.webp",
    name: "Rincy",
    company: null,
    position: "Research Scientist",
    rating: 4.5,
  },
  {
    id: 17,
    comment: "Got exactly what I wanted, and it looks so realistic.",
    headshot: "/examples/ai-portrait-17.jpg",
    avatar: "/examples/avatars/ai-portrait-17.webp",
    name: "Jessica Lee",
    company: "ForgeTech",
    position: "Account Executive",
    rating: 4,
  },
  {
    id: 18,
    comment: "Affordable alternative to a professional photographer.",
    headshot: "/examples/ai-portrait-18.jpg",
    avatar: "/examples/avatars/ai-portrait-18.webp",
    name: "S. Haru",
    company: null,
    position: "Event Manager",
    rating: 5,
  },
  {
    id: 19,
    comment: "The headshots were sharp and looked completely natural.",
    headshot: "/examples/ai-portrait-19.jpg",
    avatar: "/examples/avatars/ai-portrait-19.webp",
    name: "Henrik dK",
    company: null,
    position: "Environmentalist",
    rating: 5,
  },
  {
    id: 20,
    comment: "Excellent service, my headshot looks fantastic.",
    headshot: "/examples/ai-portrait-20.jpg",
    avatar: "/examples/avatars/ai-portrait-20.webp",
    name: "Lucas Young",
    company: "Skyline Consultants",
    position: "Business Strategist",
    rating: 4.5,
  },
  {
    id: 21,
    comment: "Looks like a real photograph—very happy with the results.",
    headshot: "/examples/ai-portrait-21.jpg",
    avatar: "/examples/avatars/ai-portrait-21.webp",
    name: "Noah Ramirez",
    company: null,
    position: "Software Engineer",
    rating: 5,
  },
  {
    id: 22,
    comment: "The AI did an amazing job, my headshot is perfect.",
    headshot: "/examples/ai-portrait-22.jpg",
    avatar: "/examples/avatars/ai-portrait-22.webp",
    name: "John Mitchell",
    company: null,
    position: "Medicine",
    rating: 4,
  },
  {
    id: 23,
    // comment: "Such a seamless experience, and the quality is superb.",
    comment: "",
    headshot: "/examples/ai-portrait-23.jpg",
    avatar: "/examples/avatars/ai-portrait-23.webp",
    name: "Chris Sands",
    company: "SupportPay",
    position: "Consumer Growth",
    rating: 5,
  },
  {
    latestModel: false,
    id: 24,
    comment: "Loved the quick delivery and high resolution.",
    headshot: "/examples/ai-portrait-24.jpg",
    avatar: "/examples/avatars/ai-portrait-24.webp",
    name: "K. Pradhan",
    company: "BrightTree",
    position: "Communications Lead",
    rating: 5,
  },
  {
    latestModel: false,
    id: 25,
    // comment: "Better than I expected—sharp, clear, and realistic.",
    comment: "",
    headshot: "/examples/ai-portrait-25.jpg",
    avatar: "/examples/avatars/ai-portrait-25.webp",
    name: "Constantin Ursu",
    company: null,
    position: null,
    rating: 5,
  },
];
