"use client";

import Image from "next/image";
import {
  Carousel,
  CarouselContent,
  CarouselItem,
  CarouselNext,
  CarouselPrevious,
} from "@/components/ui/carousel";
import { Card, CardContent } from "@/components/ui/card";
import { Quote } from "lucide-react";

const testimonials = [
  {
    id: 1,
    name: "Brian",
    position: "Operations Management",
    company: "Amazon",
    image: "/examples/ai-portrait-15.jpg",
    quote:
      "I needed a professional headshot for my online presence but didn't have the time for a traditional photo shoot. proshoot.co saved the day! The AI-generated image was flawless and It captured my essence perfectly. The attention to detail and realism makes it a winner in my book.",
  },
  {
    id: 2,
    name: "Sarah",
    position: "Marketing Director",
    company: "TechCorp",
    image: "/examples/ai-portrait-1.jpg",
    quote:
      "The AI headshots generated by proshoot.co are incredibly lifelike. They've helped our entire marketing team maintain a consistent, professional image across all our channels.",
  },
  {
    id: 3,
    name: "Michael",
    position: "Senior Developer",
    company: "StartupHub",
    image: "/examples/ai-portrait-23.jpg",
    quote:
      "As a remote worker, having a professional headshot is crucial. proshoot.co made it possible to get a studio-quality photo without leaving my home office.",
  },
];

export default function TestimonialsCarousel() {
  return (
    <section className="relative overflow-hidden bg-gradient-to-b from-secondary to-background py-16 sm:py-24">
      <div className="container px-4 py-12 sm:px-6 lg:px-8 lg:pt-16 lg:pb-28 mx-auto">
        <Carousel className="w-full">
          <CarouselContent>
            {testimonials.map((testimonial) => (
              <CarouselItem key={testimonial.id}>
                <Card className="border-none bg-transparent">
                  <CardContent className="p-0">
                    <div className="lg:grid lg:grid-cols-6 lg:gap-8 lg:items-center">
                      <div className="hidden lg:block lg:col-span-2">
                        <Image
                          className="rounded-lg shadow-lg"
                          src={testimonial.image}
                          alt={`${testimonial.name}'s professional headshot`}
                          width={512}
                          height={512}
                          quality={100}
                        />
                      </div>

                      <div className="lg:col-span-4">
                        <blockquote>
                          <Quote
                            className="scale-[-1] text-destructive block lg:hidden xl:hidden 2xl:block ml-[-5px]"
                            width={48}
                            height={48}
                            strokeWidth={1.5}
                          />
                          <p
                            className={`text-xl font-medium lg:text-2xl lg:leading-normal`}
                          >
                            {testimonial.quote
                              .split("proshoot.co")
                              .map((part, i, arr) => (
                                <span key={i}>
                                  {part}
                                  {i < arr.length - 1 && (
                                    <span className="bg-gradient-to-r from-primary to-primary/80 bg-clip-text text-transparent">
                                      proshoot.co
                                    </span>
                                  )}
                                </span>
                              ))}
                          </p>
                          <footer className="mt-6">
                            <div className="flex items-center">
                              <div className="lg:hidden flex-shrink-0">
                                <Image
                                  className="h-12 w-12 rounded-full object-cover"
                                  src={testimonial.image}
                                  alt={`${testimonial.name}'s professional headshot`}
                                  height={48}
                                  width={48}
                                />
                              </div>
                              <div className="ms-4 lg:ms-0">
                                <div
                                  className={`font-medium text-foreground flex gap-2`}
                                >
                                  {testimonial.name}
                                </div>
                                <p className="text-sm text-muted-foreground">
                                  {testimonial.position}, {testimonial.company}
                                  {testimonial.company === "Amazon" && (
                                    <sup>®</sup>
                                  )}
                                </p>
                              </div>
                            </div>
                          </footer>
                        </blockquote>
                      </div>
                    </div>
                  </CardContent>
                </Card>
              </CarouselItem>
            ))}
          </CarouselContent>
          {/* <div className="hidden sm:block"> */}
          <CarouselPrevious className="top-full left-1/3" />
          <CarouselNext className="top-full right-1/3" />
          {/* </div> */}
        </Carousel>
      </div>
    </section>
  );
}
